server:
  port: 9997
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://47.100.238.158:3306/ly
    username: root
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka
    instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1


mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl